spring.datasource.url=jdbc:postgresql://localhost:5432/hoteldb
spring.datasource.username=hotel
spring.datasource.password=hotel123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=hotel-core-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sistema.gestao.sistemagestao.event,com.hotel.pagamentos.event
spring.kafka.consumer.properties.spring.json.value.default.type=com.sistema.gestao.sistemagestao.event.PagamentoResultadoEvent

kafka.topics.reserva-criada=reserva.criada
kafka.topics.pagamento-resultado=pagamento.resultado
<<<<<<< HEAD

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

=======
>>>>>>> 25c1116d5d642c79d6a6db540df18b38f8ad5f3c
